name: Python SonarQube Scan321

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install pytest and coverage
        run: pip install pytest coverage

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml  # This generates coverage.xml for SonarQube analysis
          pytest --junitxml=pytest.xml  # Generates JUnit-style test report

      - name: Install Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
          unzip dependency-check-10.0.4-release.zip
          sudo mv dependency-check /usr/local/bin/

      - name: Run Dependency-Check
        run: |
          /usr/local/bin/dependency-check/bin/dependency-check.sh \
            --project "Test1" \
            --scan . \
            --format HTML \
            --out dependency-check-report.html

      - name: Install Sonar Scanner
        run: pip install pysonar-scanner

      - name: Run SonarQube analysis
        run: |
          pysonar-scanner \
          -Dsonar.projectKey=python \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://f296-59-145-123-10.ngrok-free.app \
          -Dsonar.token=sqp_b816eb40a95284ef0d65600071dcb50b3af6bc51 \
          -Dsonar.javascript.node.maxspace=8192 \
          -Dsonar.dependencyCheck.summarize=true \
          -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html \
          -Dsonar.python.coverage.reportPaths=coverage.xml \
          -Dsonar.python.xunit.reportPath=pytest.xml
