name: Python SonarQube Scan

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.2/dependency-check-8.1.2-release.zip
          unzip dependency-check-8.1.2-release.zip
          sudo mv dependency-check /usr/local/bin/

      - name: Run Dependency-Check
        run: |
          /usr/local/bin/dependency-check/bin/dependency-check.sh \
            --project "Test1" \
            --scan . \
            --format HTML \
            --out dependency-check-report.html


      - name: Install sonar scanner
        run: pip install pysonar-scanner

      - name: Run SonarQube analysis
        run: |
         pysonar-scanner \
         -Dsonar.projectKey=Test1 \
         -Dsonar.sources=. \
         -Dsonar.host.url=http://13.126.193.120:9000/ \
         -Dsonar.login=sqa_be7f5853b2ee73a56e10e61ff99021f0451da1ec 
         -Dsonar.javascript.node.maxspace=8192 \
         -Dsonar.dependencyCheck.summarize=true \
         -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html \
         -Dsonar.exclusions=**/*.py

      

