name: Python SonarQube Scan1

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Use the Python version you need

      # Cache for Python dependencies
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Cache for Dependency-Check
      - name: Cache Dependency-Check data
        uses: actions/cache@v3
        with:
          path: ~/.cache/owasp/dependency-check/data
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-

      - name: Install Dependency-Check if not cached
        run: |
          if [ ! -d "/usr/local/bin/dependency-check" ]; then
            wget https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check-10.0.4-release.zip
            unzip dependency-check-10.0.4-release.zip
            sudo mv dependency-check /usr/local/bin/
          fi

      - name: Run Dependency-Check
        run: |
          /usr/local/bin/dependency-check/bin/dependency-check.sh \
            --project "python" \
            --scan . \
            --format HTML \
            --out dependency-check-report.html

      # Cache for SonarQube analysis (optional, if any large files or tools are reused)
      - name: Install sonar scanner
        run: pip install pysonar-scanner

      - name: Run SonarQube analysis
        run: |
         pysonar-scanner \
         -Dsonar.projectKey=python \
         -Dsonar.sources=. \
         -Dsonar.host.url=https://9d81-59-145-123-10.ngrok-free.app \
         -Dsonar.token=sqp_b816eb40a95284ef0d65600071dcb50b3af6bc51 \
         -Dsonar.dependencyCheck.summarize=true \
         -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html
